### ISSUE TITLE
Merge/combine search-for-domgraph-nodes.py and search-for-domgraph-nodes-multi.py

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#10]
We now have two scripts to benchmark search against a domgraph - search-for-domgraph-nodes.py and search-for-domgraph-nodes.multi.py.

The first script takes a catlas, a query minhash, and a label ID, and computes statistics on using the query to search the minhash, and then compares the results to the label.

The second script does the same, but takes many query minhashes, so it only loads the catlas once. It's must faster for bulk queries.  The downside is that at the moment it doesn't take any labels, so it just infers the label ID from the order of the input queries.  This isn't very flexible but seems to match my current major use case.

I think we can merge the scripts (and their behaviors) if we provide a way to set a single label to search for; the default would be to infer the label IDs from the input minhash list, but if --search-labels is set to then assume we're looking for a single label.

**Comment by domoritz** [comment]
We don't use this search anymore.
