### ISSUE TITLE
'from typing import DefaultDict' fails on Python 3.5.0

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#107]
in rdomset.py -- and it turns out it's not used anyway...

**Comment by domoritz** [comment]
I think I fixed that on master. It was working a few days ago and then there was probably an update of mypy that broke things.

**Comment by domoritz** [comment]
https://github.com/spacegraphcats/spacegraphcats/commit/a211625bc985796352b31759d8dec31e97608d9f

**Comment by ctb** [comment]
see b5520f4b89
