### ISSUE TITLE
Update tests to run a basic workflow

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#108]
This would be more of an integration test, but I think it's valuable to have it in there!

TODO:

- [ ] compare against saved/check for regressions
- [ ] add a search

**Comment by domoritz** [comment]
Yeah, I would like us to run it and compare the output to some saved output in the repo. We do something like that in Vega-Lite and it has helped us a lot to prevent regressions.

**Comment by ctb** [comment]
+1
