### ISSUE TITLE
incomplete containment of reads by cDBG minhash

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#119]
On "real read" data sets (shewanella and podar) I have seen that fewer than 100% of the k-mers in the reads are contained in the cDBG (see for example https://github.com/spacegraphcats/spacegraphcats/issues/71#issuecomment-298891733). I just verified that this is because the contigs output by walk_dbg don't contain all the k-mers.

specifically, 
```
# build minhash of the reads
% sourmash compute -k 31 --scaled 1000 shewanella.abundtrim.gz
# build minhash of the contigs
% sourmash compute -k 31 --scaled 1000 shew-reads/contigs.fa.gz -o shew-contigs.sig
# compare
% sourmash search shew-contigs.sig shewanella.abundtrim.gz.sig
# running sourmash subcommand: search
loaded query: shew-reads/contigs.fa.gz... (k=31, DNA)
loading db of signatures from 1 files
loaded 1 signatures total.
1 matches; showing 3:
         shewanella.abundtrim.gz         0.990   shewanella.abundtrim.gz.sig
```

So this is a bug in walk_dbg.

**Comment by ctb** [comment]
It's also asymmetric which is weird... neither contains the other!?

```
sourmash search shew-contigs.sig shewanella.abundtrim.gz.sig --containment
# running sourmash subcommand: search
loaded query: shew-reads/contigs.fa.gz... (k=31, DNA)
loading db of signatures from 1 files
loaded 1 signatures total.
1 matches; showing 3:
         shewanella.abundtrim.gz         0.992   shewanella.abundtrim.gz.sig
```

% sourmash search shewanella.abundtrim.gz.sig shew-contigs.sig --containment
# running sourmash subcommand: search
loaded query: shewanella.abundtrim.gz... (k=31, DNA)
loading db of signatures from 1 files
loaded 1 signatures total.
1 matches; showing 3:
         shew-reads/contigs.fa.gz        0.998   shew-contigs.sig
```

**Comment by ctb** [comment]
Hmm, one thought is that I use high degree nodes to traverse from. So if there are isolated linear regions that have no high degree nodes, we won't have any handle on them.

**Comment by ctb** [comment]
A quick test shows that this could definitely be one problem.

**Comment by bdsullivan** [comment]
@ctb is this fixed now?

**Comment by ctb** [comment]
verifying the fix now; had to back out some commits due to a performance regression (major slowdown) in khmer, which blew about 2 hours of my time today (Tracking it own). Sigh.

**Comment by ctb** [comment]
The primary fix is here, https://github.com/dib-lab/khmer/pull/1793, along with #130.

**Comment by ctb** [comment]
Note that the `extract_reads_by_frontier` script now checks the containment of the output reads, and prints a warning if it is different from the containment of the frontier.
