### ISSUE TITLE
pretreatment: should we remove 16s (highly repetitive) from data before cDBG?

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#121]
this might simplify the catlas a lot.

**Comment by sgsmob** [comment]
16s?

**Comment by ctb** [comment]
highly repetitive biological sequences present in every bacterium.  not
useful for our purposes.  see https://en.wikipedia.org/wiki/16S_ribosomal_RNA

**Comment by sgsmob** [comment]
If they are not crucial to the biological analysis, then I think we should.

**Comment by bdsullivan** [comment]
I think I concur with @sgsmob, but want to make sure this isn't going to invalid our assumption that locality in the cDBG is meaningful. I guess what I'm worried about is that we have some organism whose sequence data gets disconnected (when viewed as an induced subgraph) once we remove the 16S sequences.

**Comment by ctb** [comment]
Yes, good concerns. I was putting this down more as a note of something to try
than anything else.

**Comment by taylorreiter** [comment]
I have lost a lot of sleep over this question over the past year or so. 

16S/23S etc. run the risk of getting scooped in to nbhds where they don't really belong. This probably isn't a huge problem when R=1, but I could see it becoming a problem at larger radius sizes, e.g. R=10, especially for genomes present in metagenomes that has low strain variation and 16S sequence. I could dream of a situation where whole swaths of sequence may get grouped together from not very closely related organisms, and returned in query neighborhoods. 

However, these are also biologically important sequences that could be important to consider in a large-scale analysis -- if they're just ignored by spacegraphcats, they may get systematically missed, leading to biases in biological results.

**Comment by ctb** [comment]
right, I think your work on IBD suggests we need to leave this in, in fact!
