### ISSUE TITLE
idle thoughts about dom radius r, and the frontier search overhead

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#124]
was thinking about this on the plane yesterday - the lead-in question was, why are we getting non-zero overhead when we ask for 0 overhead on a frontier search for a query that is 100% in the dataset?

the answer, I think, is that the only source of overhead when frontier search overhead is 0 is the dominating set leaf nodes - the dominating nodes will necessarily include cDBG nodes that are not part of the query.  so if I am right, one thing we will need to examine is the effect of different r on "0 overhead" frontier search queries.

**Comment by sgsmob** [comment]
Yes this is definitely correct

**Comment by ctb** [comment]
excellent!

**Comment by domoritz** [comment]
Also confirming. If you want 0 overhead, we have to go down to the cDBG nodes.

**Comment by ctb** [comment]
ok. will develop some scripts with this in mind.
