### ISSUE TITLE
Create Logfile 

### ISSUE THREAD

**Issue by bdsullivan** [spacegraphcats/spacegraphcats#128]
From discussion in #126. 

Add provenance info to the catlas directory so we can see what commands were run (e.g. what memory size was used with walk_dbg, on what input files and with what other parameters; same for each construction step).

Suggestion: simple logfile to which we append; include the full sys.argv of each run along with (maybe) the git commit of spacegraphcats that we used.

**Comment by sgsmob** [comment]
Fixed in #129
