### ISSUE TITLE
frontier search recovers too many nodes with 0-size minhash

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#140]
I've been running frontier search with individual genome signatures against the entire podar data set for the purpose of extracting reads (using PR #139 code), and the majority of the frontier that it's recovering consists of "empty" catlas nodes -- see last line in the output below.

```
% python -m search.extract_reads_by_frontier 63-os223.sig podarV 0.2 -k 31 SRR606249.pe.qc.fastq.abundtrim.gz podarV.labels podarV.frontier.63.fq
loaded 4632354 nodes from catlas podarV/catlas.csv
loaded 2718458 layer 0 catlas nodes
...corresponding to 16799339 cDBG nodes.
loaded query sig CP001071.1 Akkermansia muciniphila ATCC BAA-835, complete genome
Root containment: 0.9708029197080292
Root similarity: 0.008467292694572656
Containment of frontier: 0.9708029197080292
Similarity of frontier: 0.9637681159420289
Size of frontier: 884089 of 4632354 (19.1%)
Overhead of frontier: 0.007462686567164179
Number of leaves in the frontier: 4
Number of empty catlas nodes in the frontier: 883765
```

Here, we retrieve 884,089 nodes in the frontier but 883,765 of them are empty!!

This is presumably because these nodes add no overhead to the frontier, and so are always safe to add.

This does cause a problem when doing read retrieval, though, because the nodes are only empty of MinHashes, not of k-mers. So when we pull in reads that belong to those catlas nodes, 

----

The behavior can be reproduced on a much smaller data set like so; this takes only a few seconds.

Download and unpack data set `twofoo-catlas-and-reads.tar.gz` from [here](https://osf.io/jqtxc/download) (~80 MB), as well as signature `63-os223.sig` from [here](https://osf.io/rzw7k/download), and then run:

```
% python -m search.frontier_search 63-os223.sig twofoo 0.1 -k 21
loaded 301264 nodes from catlas twofoo/catlas.csv
loaded query sig NC_011663.1 Shewanella baltica OS223, complete genome
Root containment: 0.9363704819277109
Root similarity: 0.501714746822675
Containment of frontier: 0.9363704819277109
Similarity of frontier: 0.9248791372257344
Size of frontier: 3265 of 301264 (1.08%)
Overhead of frontier: 0.013095238095238096
Number of leaves in the frontier: 51
Number of empty catlas nodes in the frontier: 1160

Size of query minhash: 2656 (est 5.3e+06 bp)
Size of frontier minhash: 2520 (est 5.0e+06 bp); ratio 0.95
```

(Here only 1160 of the 3265 frontier nodes are empty.)

**Comment by ctb** [comment]
A couple of thoughts come to mind:

* there needs to be a balance between adding empty catlas nodes and ignoring them. The ones that are "within" the extent of the query definitely needed to be added, as they are an important part of the generalization of a search. I don't know how to define "within the extent" clearly with respect to the catlas structure.

* one possible solution is to increase the resolution of the MinHashes as we go down the tree, but this gets a bit unwieldy and still wouldn't solve the problem in highly articulated portions of the cDBG (places where we have many small nodes).

* we could also run the search, pull out the sequences of the found nodes from contigs.fa.gz, and do a higher-resolution search "on the fly". We would ultimately be limited by the resolution of the query signature, though; if there was a B/scaled value of 10,000 on the catlas minhashes, and 1000 on the query minhashes, we couldn't go below 1000 in our query no matter what.

**Comment by sgsmob** [comment]
How can a node have an empty minhash but not an empty k-mer set?

**Comment by ctb** [comment]
every node has at least one k-mer, no? :)

MinHash in general, and banded minhash in particular, subsamples from the space of k-mers. In the case of a --scaled value of 1000, you are picking 1-in-1000 k-mers to represent that node.  So, on average, for every 1000 k-mers you get one entry in the minhash.  (It's Poisson distributed.)

**Comment by sgsmob** [comment]
The banded minhash is the part I was missing.  If we used traditional minhashing, then there would never be an empty minhash, correct?

**Comment by ctb** [comment]
That is correct! OTOH if we weren't using banded minhashes we wouldn't be able to do the containment check we use for frontier search :)

**Comment by microgravitas** [comment]
Would it be useful to keep both a banded minhash and a normal minhash per node? That way we have a change of futher distinguishing 'empty' nodes.

**Comment by ctb** [comment]
interesting idea... will muse on 't.

**Comment by ctb** [comment]
could also add a small penalty for each empty node, either as part of the
minhash overhead compute or just overall.

**Comment by ctb** [comment]
hackity hack: just added in something that removes all zero-size nodes in the frontier, so as to give it a try. 

Important point: we would still be including all zero-size leaves that are under a non-zero-size node in the frontier.

Note that setting `include_empty=False` in `frontier_search` doesn't actually eliminate all of the empty nodes in the frontier. Can't figure out why from the code.

```
loaded 4632354 nodes from catlas podarV/catlas.csv
loaded 2718458 layer 0 catlas nodes
...corresponding to 16799339 cDBG nodes.
loaded query sig NC_011663.1 Shewanella baltica OS223, complete genome
Root containment: 0.9527272727272728
Root similarity: 0.016670378264880856
Containment of frontier: 0.9527272727272728
Similarity of frontier: 0.9424460431654677
Size of frontier: 1209118 of 4632354 (26.1%)
Overhead of frontier: 0.011320754716981131
Number of leaves in the frontier: 3
Number of empty catlas nodes in the frontier: 1208465

removing...
...went from 1209118 to 653
Size of the frontier shadow: 33964
Size of query minhash: 2607 (est 5.2e+06 bp)
Size of frontier minhash: 530 (est 5.3e+06 bp); ratio 1.02
loading graph & labels/foo...
```

**Comment by ctb** [comment]
the hack above (removing all 0-size frontier nodes before calculating the shadow) makes read extraction feasible, so it's OK for the short term. Onwards!

**Comment by ctb** [comment]
Closing until we need to revisit (if we do).
