### ISSUE TITLE
CAtlas level indexing

### ISSUE THREAD

**Issue by sgsmob** [spacegraphcats/spacegraphcats#143]
As implemented, the CAtlas defines the leaves (r-domset of the cDBG) to be the level 0 nodes.  For ease of description, however, I think it would make more sense to start the indexing at 1.  Conceptually, the CAtlas has a level below what is currently the leaves in which each node is a vertex from the cDBG and the parent is the first dominator in the original cDBG; we choose not to store this in a large part for space reasons.  To more easily describe mathematically how the construction of the CAtlas is the same at all levels, it would be better to refer to this non-existent level as level 0 and go upwards.  I think it is important to make sure our indexing in the paper lines up with the indexing in the code, so I would like to make this change soon.

**Comment by bdsullivan** [comment]
@sgsmob I assume this change wouldn't affect any functionality, other than maybe some indexing in scripts that @ctb is running? I'm in favor of the change to make it easier to describe conceptually.

**Comment by sgsmob** [comment]
Yes this would not affect functionality, but may require touching a lot of scripts depending on how many of them are actually using the level information.

**Comment by ctb** [comment]
+1 @sgsmob shouldn't affect any of my scripts, and if it does it'll be an easy fix.
