### ISSUE TITLE
load_query_signature: change select_ksize to ksize

### ISSUE THREAD

**Issue by bluegenes** [spacegraphcats/spacegraphcats#145]
Wherever load_query_signature() from sourmash_lib.sourmash_args is used, the `select_ksize` argument needs to be changed to `ksize` to reflect recent syntax change

**Comment by ctb** [comment]
Yes! But for now the spacegraphcats branch of sourmash should work.

--
Titus Brown, ctbrown@ucdavis.edu

**Comment by bluegenes** [comment]
yep

**Comment by ctb** [comment]
Done! https://github.com/spacegraphcats/spacegraphcats/commit/696589cdaf297736977fb5c4116ed09a03362e65
