### ISSUE TITLE
Investigate murmurhash biases for seed=42

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#153]
are we maybe getting biases in what goes into our band?

c.f. https://github.com/dib-lab/sourmash/issues/187

**Comment by ctb** [comment]
also see if we can resurrect david koslicki's relevant blog post comment (for @ctb to do)

**Comment by ctb** [comment]
Interestingly, this question came up over on khmer: https://github.com/dib-lab/khmer/pull/1792#issuecomment-338994016

**Comment by ctb** [comment]
(There are some pretty graphs in that comment showing pretty even representation of hashes across bins.)

**Comment by betatim** [comment]
Your [comment](https://github.com/dib-lab/khmer/pull/1792#issuecomment-339106105) about XOR'ing makes me wonder: does your bias go away if you compute the hash of forward and reverse with different seeds? Thinking: XOR works if the two values are random (aka independent) but reverse and forward kmer are 100% correlated and if both use the same seed, do we get something where the bits aren't uncorrelated -> forward ^ reverse isn't a random number anymore? #speculating

**Comment by ctb** [comment]
no longer relevant.
