### ISSUE TITLE
Search-dbg.py output

### ISSUE THREAD

**Issue by Kevinlega** [spacegraphcats/spacegraphcats#18]
When you have both True Positives and False Negatives equal zero it gives the error that is dividing by zero when we calculate the sensitivity. When you have True Negative and False Positives equal zero it divides by zero in specificity. I fixed the issue on the script I'll send a pull request.

**Comment by domoritz** [comment]
We can't find the pull request for this issue but suspect that this is not relevant anymore as we changed the code.
