### ISSUE TITLE
Contract again after noise removal

### ISSUE THREAD

**Issue by domoritz** [spacegraphcats/spacegraphcats#187]

**Comment by sgsmob** [comment]
It seems there may be some limitations to this method that I had not thought about yet.
podarV that has a "thin path" (degree 2 vertices only) consisting of vertices 55, 54, and 10440315 (in that order).  These are their corresponding lines in the BCALM file.
```
>55 LN:i:33 KC:i:3 km:f:1.0  L:-:54:-  L:+:7425592:+
GCTTTTAACACGGTTAGAGCCTGACGCGGCACC

>54 LN:i:40 KC:i:12 km:f:1.2   L:+:55:+ L:+:10440315:+
CGCTGCCGCCGCTTTTAACACGGTTAGAGCCTGACGCGGC

>10440315 LN:i:68 KC:i:38 km:f:1.0  L:-:54:-  L:+:4952921:+
GCTTTTAACACGGTTAGAGCCTGACGCGGCCCCTTATACGGTCCATCCCTTTTTTTAGCAAAAAAATT
```
The suffix of 54 (`GCTTTTAACACGGTTAGAGCCTGACGCGGC`) matches both the prefix of 55 and the prefix of 10440315, so 54 is adjacent to both.  So if we were to treat the cBDG as a directed graph, we would have the subgraph `10440315 <- 54 -> 55`, which does not form a directed path and thus cannot be combined to form a single unitig.

I think we should be ok just to leave these in the graph, but it does counter our intuition that an (untrimmed) cDBG has no thin paths.

**Comment by ctb** [comment]
Right - this makes sense to me. I think I am not good at taking into account sequence orientation in thinking about these graphs.

**Comment by ctb** [comment]
(i.e. just leave it in the graph)
