### ISSUE TITLE
search and searchquick in Snakefile use extract_nodes_by_query

### ISSUE THREAD

**Issue by drtamermansour** [spacegraphcats/spacegraphcats#194]
The search and searchquick rules in the Snakefile call the same python script in the shell command:

```
rule searchquick:
    ...
    shell:
        "{python} -m search.extract_nodes_by_query {catlas_dir} {search_dir} --query {config[searchquick]} -k {ksize} --overhead={overhead}"
```
```
rule search:
    ...
    shell:
        "{python} -m search.extract_nodes_by_query {catlas_dir} {search_dir} --query {config[search]} -k {ksize} --overhead={overhead}"
```

I think the search rule should use extract_contigs_cdbg.py

**Comment by ctb** [comment]
see `config[searchquick]` difference - the idea is that you can have a few search genomes specified in the JSON file under `searchquick` for testing purposes. I use it fairly frequently.
