### ISSUE TITLE
change reads output filename

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#229]
After merge of #228, output reads are FASTQ if input reads are FASTQ. However, the filename specified by `conf/Snakefile` for `extract_reads.py` is still .fa.gz. For version 2, we should change this.

**Comment by taylorreiter** [comment]
Yes plz :)

See https://github.com/wwood/singlem/issues/52 for downstream problems this can cause.

**Comment by ctb** [comment]
...are you sure that's the right link?

**Comment by taylorreiter** [comment]
Yes! https://github.com/wwood/singlem/issues/52#issuecomment-664677243

The issue turned out to be two issues in one, where the first problem was having the wrong file name ending.

**Comment by ctb** [comment]
#344 changes the output name to `reads.gz`, no .fa or .fq.

why this?
* screed doesn't care what the name is
* snakemake doesn't really like it when the output names are unknown 😆 
* we don't really have the information as to what the format of the reads is, in general

so, my suggestion is that people using this should just rename or `ln` the file to what they know the output should be (e.g. fq.gz)
