### ISSUE TITLE
Snakemake error

### ISSUE THREAD

**Issue by susheelbhanu** [spacegraphcats/spacegraphcats#230]
Hello, 

I was trying to run the test after the installation, and I get a 'snakemake' error as follows:

 ```
File /mnt/lscratch/users/sbusi/extraction_methods/fastq_NewZealand/cats/spacegraphcats/spacegraphcats/__main__.py, line 7, in <module>
    import snakemake
ModuleNotFoundError: No module named 'snakemake'
```

I have a Python3.6 library in my environment. 

Is there something else that needs to be loaded, apart from bcalm?

Thank you,
Susheel

**Comment by domoritz** [comment]
Please make sure that you have the dependencies from the requirements file installed: https://github.com/spacegraphcats/spacegraphcats/blob/master/requirements.txt

**Comment by susheelbhanu** [comment]
Thanks a lot Dominik, but I did the following:

```pip install -r requirements.txt```

It didn't throw any errors.

**Comment by domoritz** [comment]
That's odd. It looks like your python cannot find the installed package then. 

Can you try this: 

```
pip install snakemake
python -c 'import snakemake'
```

**Comment by domoritz** [comment]
If that works, maybe you need to update your dependencies with `pip install -U -r requirements.txt`.

**Comment by susheelbhanu** [comment]
You're right.. I'm trying to run this on a HPC, and looks like I had issues installing the snakemake in the first place ```PermissionError: [Errno 13] Permission denied: '/opt/apps/resif/data/production/v1.1-20180716/default/software/lang/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/wrapt-1.11.2.dist-info'```

Will check in with the admins in the morning!

Thanks again, Dominik!

**Comment by domoritz** [comment]
If you're running on a shared system, I'd highly recommend using a virtual environment with isolated dependencies. The specifics of how you do this vary but there is are a lot of resources on this on the internet.

@ctb Would it make sense to fix the dependencies better with something like pipenv?

**Comment by susheelbhanu** [comment]
I did exactly that - a virtual environment, and reloaded a different version of Python (3.7 with GCC). So far the snakemake installation worked out. Had to install 'screed,  'sourmash', and bbhash with pip install <package> --user

Finally have a successful test:
```
...fetched 2 contigs, 1671 bp matching combined frontiers.  (0.0s)
query inclusion by retrieved contigs: 100.000%
query similarity to retrieved contigs: 100.000%
total time: 0.0s
=> containment: 100.0%
cdbg match node similarity: 100.0%
min cdbg overhead: 0.0
minimum catlas overhead: 0.0
[Wed Sep  4 22:32:28 2019]
Finished job 0.
2 of 2 steps (100%) done
Complete log: /mnt/lscratch/users/sbusi/extraction_methods/fastq_NewZealand/cats/spacegraphcats/.snakemake/log/2019-09-04T223226.982178.snakemake.log

-------- DONE --------

catlas output directory: dory_k21_r1
search output directory: dory_k21_r1_search_oh0```

Thanks a lot for all the input and help, Dominik!

Thanks!

**Comment by domoritz** [comment]
Sweet. I'll close the issue then.
