### ISSUE TITLE
Producing fastq reads as output format

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#237]
#228 outputs a fastq if input reads are fastq. Does the query also need to be in fastq format? I recently ran spacegraphcats and was hoping to get fastq format, but received fasta format out of the tool 

```
['/home/tereiter/miniconda3/lib/python3.7/site-packages/spacegraphcats/search/query_by_sequence.py', 'SRR7658687_k31_r1', 'SRR7658687_k31_r1_search_oh0', '--query', 'A02_01_1FE__bin.7-pgaA_query.fa', '-k', '31']
```

I'm not sure how to check the version of the tool, as there is a chance that I installed from pip and this feature is not yet implemented there.

**Comment by ctb** [comment]
The code that extracts reads is `extract_reads`, and that should return FASTQ if it's available. `query_by_sequence` doesn't produce sequence output.

You can get the spacegraphcats version by doing `--version` now :).

I'll close this for now and please reopen if you run into the same problem.
