### ISSUE TITLE
Enable multiple radii in a single conf file

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#239]
With conf file:
```
input_sequences:
- fastq/PSM6XBTR.fastq.gz
ksize: 31
radius:
- 1
- 5
- 10
search:
- ~/github/spacegraphcats/data/2.fa.gz
searchquick:
- ~/github/spacegraphcats/data/63.fa.gz

hashval_ksize: 51
hashval_queries: ../calc_cosmo_kmers/hmp_scaled2k_th138.labels.txt
```

I receive the following error message:
```
/home/tereiter/miniconda3/envs/sgc_hq/bin/python -m spacegraphcats.cdbg.bcalm_to_gxt  -k 31 PSM6XBTR/bcalm.PSM6XBTR.k31.unitigs.fa PSM6XBTR_k31_r[1, 5, 10]/cdbg.gxt PSM6XBTR_k31_r[1, 5, 10]/contigs.fa.gz
usage: bcalm_to_gxt.py [-h] [-k KSIZE] [-d] [-P] [-a [ABUNDANCE]]
                       [--randomize RANDOMIZE]
                       bcalm_unitigs gxt_out contigs_out
bcalm_to_gxt.py: error: unrecognized arguments: 10]/cdbg.gxt PSM6XBTR_k31_r[1, 5, 10]/contigs.fa.gz
```

It would be great if all radii could be included in one conf file, producing output directories like this:
```
PSM6XBTR_k31_r1_hashval_k51
PSM6XBTR_k31_r5_hashval_k51
PSM6XBTR_k31_r10_hashval_k51
```

**Comment by ctb** [comment]
A few random thoughts -

* there's no gain (or loss :) in efficiency in doing things this way - the snakemake wf already reuses the relevant underlying files (which is mostly the cDBG)
* there might be significant gain in complexity, but I wonder if it could be limited to the snakefile?
* so... how would queries work? would you then do queries against all radii? that sounds complicated and potentially time consuming

**Comment by taylorreiter** [comment]
Ah I didn't think about how queries would work. Queries would be complicated and time consuming if multiple radii were in one conf file. I think because snakemake already reuses the relevant underlying files, this is already great the way it is. Thanks!
