### ISSUE TITLE
Remove? top level conf directory

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#240]
Right now we have config files in two places, `./conf` and `./spacegraphcats/conf`. The latter are nicer (YAML) config files etc., and can be found without specifying a path. What should we do?

**Comment by taylorreiter** [comment]
I think I like having all config files in `./spacegraphcats/conf`. The current organization was confusing to me as I was trying to find example config files, and as some worked without path and some didn't.
