### ISSUE TITLE
The 'spacegraphcats' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by jervermex** [spacegraphcats/spacegraphcats#244]
Dear all

I'm tryning to install spacegraphcats on our own cluster, with conda ( Miniconda).
UI create an special environment for spacegraphcats.
All the process of instalation seems to work correctly. 
At the moment to run the tests, i've got this error:

pkg_resources.DistributionNotFound: The 'spacegraphcats' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/state/partition1/jerome/spacegraphcats/spacegraphcats/__init__.py", line 6, in <module>
    from .version import version as VERSION  # noqa
ImportError: No module named 'spacegraphcats.version'

../..

it's due to Anaconda, or something else?

best regards.

**Comment by taylorreiter** [comment]
Hi @jervermex! Can you please provide the installation code you used?

**Comment by ctb** [comment]
Note that you need to 'pip install' it somehow --

pip install -e .

in the spacegraphcats directory should work.

--t

On Mon, Oct 07, 2019 at 10:31:26AM -0700, jervermex wrote:
> Dear all
> 
> I'm tryning to install spacegraphcats on our own cluster, with conda ( Miniconda).
> UI create an special environment for spacegraphcats.
> All the process of instalation seems to work correctly. 
> At the moment to run the tests, i've got this error:
> 
> pkg_resources.DistributionNotFound: The 'spacegraphcats' distribution was not found and is required by the application
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/state/partition1/jerome/spacegraphcats/spacegraphcats/__init__.py", line 6, in <module>
>     from .version import version as VERSION  # noqa
> ImportError: No module named 'spacegraphcats.version'
> 
> ../..
> 
> it's due to Anaconda, or something else?
> 
> best regards.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/spacegraphcats/spacegraphcats/issues/244
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by jervermex** [comment]
Dear Taylor, Titus.

Here is what i do to install spacegraphcats:

I do 3 environment for 3.5, 3.6 and 3.7
$ conda create -y --name cats python=3.5
$ conda activate cats
$ git clone https://github.com/spacegraphcats/spacegraphcats/
$ cd spacegraphcats/
$ pip install -U setuptools pip
$ pip install Cython
$ pip install -r requirements.txt
(this next step don't seems to be necessary, khmer is installed berfore)..
$ pip install https://github.com/dib-lab/khmer/archive/master.zip 
$ pip install -e .

With 3.5 i've got this error:
$ python -m spacegraphcats dory-test search
Traceback (most recent call last):
  File "/share/apps/External/Miniconda3-4.7.10/envs/cats/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/share/apps/External/Miniconda3-4.7.10/envs/cats/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/state/partition1/jerome/spacegraphcats/spacegraphcats/__main__.py", line 7, in <module>
    import snakemake
  File "/share/apps/External/Miniconda3-4.7.10/envs/cats/lib/python3.5/site-packages/snakemake/__init__.py", line 21, in <module>
    from snakemake.workflow import Workflow
  File "/share/apps/External/Miniconda3-4.7.10/envs/cats/lib/python3.5/site-packages/snakemake/workflow.py", line 30, in <module>
    from snakemake.dag import DAG
  File "/share/apps/External/Miniconda3-4.7.10/envs/cats/lib/python3.5/site-packages/snakemake/dag.py", line 1533
    return f"#{hex_r:0>2X}{hex_g:0>2X}{hex_b:0>2X}"
                                                  ^
SyntaxError: invalid syntax

With Python 3.6 and 3.78 i've got this error:

# python -m spacegraphcats dory-test search
Found configfile at /state/partition1/jerome/spacegraphcats/spacegraphcats/./conf/dory-test.yaml
--------
details!
	snakefile: /state/partition1/jerome/spacegraphcats/spacegraphcats/./conf/Snakefile
	config: /state/partition1/jerome/spacegraphcats/spacegraphcats/./conf/dory-test.yaml
	targets: ['search']
--------
Traceback (most recent call last):
  File "/share/apps/External/Miniconda3-4.7.10/envs/cats/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/share/apps/External/Miniconda3-4.7.10/envs/cats/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/state/partition1/jerome/spacegraphcats/spacegraphcats/__main__.py", line 137, in <module>
    sys.exit(main())
  File "/state/partition1/jerome/spacegraphcats/spacegraphcats/__main__.py", line 129, in main
    verbose=args.verbose, debug_dag=args.debug)
TypeError: snakemake() got an unexpected keyword argument 'configfile'

I've found the dory-test.yaml file, but can't understand why it's not running.

Thank's your help!

Regards

**Comment by taylorreiter** [comment]
@jervermex for now, you can install spacegraphcats directly from pypi and it should work:

```
pip install spacegraphcats
```

@ctb i'm getting this error today too when I try to install from master:
```
TypeError: snakemake() got an unexpected keyword argument 'configfile'
```

I've tried to install all the packages as recommended:
```
conda activate space_test
conda install pip
pip install Cython
pip install https://github.com/dib-lab/pybbhash/archive/spacegraphcats.zip
pip install https://github.com/dib-lab/khmer/archive/master.zip
pip install git+https://github.com/dib-lab/sourmash@master#egg=sourmash
pip install git+https://github.com/spacegraphcats/spacegraphcats.git@master
pip install git+https://github.com/spacegraphcats/spacegraphcats.git@master
```

And I've tried to install with conda packages as dependencies:
```
conda env remove -n space_unlock
conda create -n space_unlock python=3 sourmash khmer Cython pip
pip install https://github.com/dib-lab/pybbhash/archive/spacegraphcats.zip
conda activate space_unlock
pip install https://github.com/dib-lab/pybbhash/archive/spacegraphcats.zip
pip install git+https://github.com/spacegraphcats/spacegraphcats.git@master
python -m spacegraphcats config.yaml extract_reads
```

I'm not sure what is causing it

**Comment by taylorreiter** [comment]
@ctb note I've installed from master since the latest commit (https://github.com/spacegraphcats/spacegraphcats/commit/8a74505428d305d2e4f2ad382da8f33a9d125f2d) on farm (UC Davis HPC that runs linux) and have had no issues running the hashval query commands

**Comment by Laura-Alex** [comment]
@taylorreiter

It might be a silly idea, but I've installed spacegraphcats twice recently and had the same error message with snakemake. For me, what solved it (in 1/2 cases, at least) was making sure snakemake is installed with conda (conda install -c bioconda snakemake). Sorry for butting it, I just hope it's helpful.

**Comment by ctb** [comment]
(thank you!)

**Comment by jervermex** [comment]
Le 14/10/2019 à 07:54, Laura-Alex a écrit :
> @taylorreiter <https://github.com/taylorreiter>
> 
> It might be a silly idea, but I've installed spacegraphcats twice
> recently and had the same error message with snakemake. For me, what
> solved it (in 1/2 cases, at least) was making sure snakemake is
> installed with conda (conda install -c bioconda snakemake). Sorry for
> butting it, I just hope it's helpful.
> 

Hi Laura.

The cats environment have spacegraph included, in version 5.7.0_

$ pip list | grep snake
snakemake          5.7.0



-- 
-- Jérôme
Si vous ne pouvez expliquer un concept à un enfant de six ans,
c'est que vous ne le comprenez pas complètement.
	(Albert Einstein)

**Comment by taylorreiter** [comment]
Hi @Laura-Alex and @jervermex! Thank you both for your input. Previously, our `requirements.txt` file only specified `snakemake` for installation, meaning pip would install the latest version. Last week, snakemake version 5.7.0 was released. During this release, some things broke for spacegraphcats. While we figure out what those things are and how to fix them, we've updated our master branch `requirements.txt` file to install snakemake version 5.6.0 (see #247). I don't think we have pushed this to pypi yet to make it pip installable, so in the meantime you can pip install spacegraphcats from the master branch, or change the snakemake version in your environment to 5.6.0.

Thanks for helping us catch this bug!

**Comment by jervermex** [comment]
With Snakemake 5.6.0, it's running , at least the "dory-test" .

Thank's for your help!

Regards

**Comment by ctb** [comment]
great, glad to hear it!
