### ISSUE TITLE
Update pypi spacegraphcats to specify the version of snakemake

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#248]
Snakemake version 5.7.0 breaks spacegraphcats, but our pypi install doesn't specify which version of spacegraphcats should be installed. We should probably update that...

**Comment by ctb** [comment]
ok, was wondering if that was a problem but didn't have time to dig in.
thanks!

On Mon, Oct 14, 2019 at 07:54:02AM -0700, Taylor Reiter wrote:
> Snakemake version 5.7.0 breaks spacegraphcats, but our pypi install doesn't specify which version of spacegraphcats should be installed. We should probably update that...
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/spacegraphcats/spacegraphcats/issues/248
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by taylorreiter** [comment]
Closed by #247
