### ISSUE TITLE
Assertion error in rule label_reads for extract_reads_for_hashvals

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#249]
With command:
```
python -m spacegraphcats --nolock inputs/conf/HSM6XRTO_r1_conf.yml extract_reads_for_hashvals
```

```
Traceback (most recent call last):
  File "/home/tereiter/miniconda3/envs/sgc_hq/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tereiter/miniconda3/envs/sgc_hq/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tereiter/miniconda3/envs/sgc_hq/lib/python3.7/site-packages/spacegraphcats/cdbg/label_cdbg.py", line 135, in <module>
    sys.exit(main())
  File "/home/tereiter/miniconda3/envs/sgc_hq/lib/python3.7/site-packages/spacegraphcats/cdbg/label_cdbg.py", line 110, in main
    for record, offset in search_utils.iterate_bgzf(reader):
  File "/home/tereiter/miniconda3/envs/sgc_hq/lib/python3.7/site-packages/spacegraphcats/search/search_utils.py", line 79, in iterate_bgzf
    for record, pos in iter_fn(reader):
  File "/home/tereiter/miniconda3/envs/sgc_hq/lib/python3.7/site-packages/spacegraphcats/search/search_utils.py", line 147, in my_fastq_iter
    assert plus == '+'
AssertionError
[Mon Oct 14 09:00:04 2019]
Error in rule label_reads:
    jobid: 19
    output: HSM6XRTO_k31_r1/reads.bgz.labels
    shell:
        /home/tereiter/miniconda3/envs/sgc_hq/bin/python -m spacegraphcats.cdbg.label_cdbg HSM6XRTO_k31_r1 HSM6XRTO/HSM6XRTO.reads.bgz HSM6XRTO
_k31_r1/reads.bgz.labels
        (exited with non-zero exit code)

Removing output files of failed job label_reads since they might be corrupted:
HSM6XRTO_k31_r1/reads.bgz.labels
```

**Comment by taylorreiter** [comment]
I ran this command on 1338 files, and this error occurred for 5 samples (fastq files) that I ran.

**Comment by taylorreiter** [comment]
This happened again on an independent project, but when I deleted all previous output files and restarted the run, it worked fine.

**Comment by taylorreiter** [comment]
I think I figured out why this error happens. When BCALM (rule `bcalm_cdbg`) is killed from too little ram but has output some legitimate files, snakemake continues on to the next rule. The failed BCALM run isn't caught until `label_reads`, when this assertion error is raised.

**Comment by ctb** [comment]
On Tue, Nov 12, 2019 at 01:07:02PM -0800, Taylor Reiter wrote:
> I think I figured out why this error happens. When BCALM (rule `bcalm_cdbg`) is killed from too little ram but has output some legitimate files, snakemake continues on to the next rule. The failed BCALM run isn't caught until `label_reads`, when this assertion error is raised. 

this should not happen, because snakemake should delete the output files
on a failed job! so if this is the case the failed exit status is not being
caught.

To me the error looks like something weird is happening with the format
for the BGZF file. Next time it happens can you save a copy of
HSM6XRTO/HSM6XRTO.reads.bgz (or whatever the reads.bgz file is)?

thx!

**Comment by ctb** [comment]
will revisit if it happens again.
