### ISSUE TITLE
Search fails and exits when 0 k-mer matches are found

### ISSUE THREAD

**Issue by taylorreiter** [spacegraphcats/spacegraphcats#254]
Right now, rule `search` fails and exits when 0 k-mers match between the query and the sample. I'm including a portion of the log file below:

```
matching ... 0^Mmatching ... 1000000^Mmatching ... 2000000^Mmatching ... 3000000^M... found 48089 matches to 30
76748 k-mers total.
matching ... 0^Mmatching ... 1000000^M... found 0 matches to 1330630 k-mers total.
[Fri Jan 10 04:07:09 2020]
Error in rule search:
    jobid: 262
```

Can this be changed to not be the default behavior? Because the pipeline is controlled by snakemake, when this error occurs, all files from successful searches are deleted and snakemake exits.

**Comment by ctb** [comment]
fixed by #255
