### ISSUE TITLE
Searching catlases with large collections of MinHashes

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#26]
Hi all,

my student @luizirber has implemented a way to search large collections of MinHashes using [Sequence Bloom Trees](http://ivory.idyll.org/blog/2015-sequence-bloom-trees-thoughts.html): see https://github.com/luizirber/2016-sbt-minhash/blob/master/notebooks/SBT%20with%20MinHash%20leaves.ipynb. It would be interesting to think about how to use this to enable catlas searches with collections of minhashes.

**Comment by ctb** [comment]
Update - see this blog post: https://github.com/ctb/titus-blog/blob/sbt/src/2016-sourmash-sbt.rst

This approach is blazingly, ridiculously fast. I'm wondering if we should replace the minhashes at each node of the catlas with bloom filters and do loading on demand... I think it might "just work"...

**Comment by domoritz** [comment]
We are closing this as we had a discussion about bloom filters and decided to use banded minhashes instead.
