### ISSUE TITLE
where is `trim-low-abund.py`? => add to docs.

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#262]
@susheelbhanu [asks](https://github.com/spacegraphcats/spacegraphcats/issues/224#issuecomment-578004571),

> I was looking for the ```trim-low-abund.py``` script. Can't seem to find it in any of the directories. I cloned the git repository, so is there something I'm missing?

it's part of khmer, so it's already installed in the environment (somewhere... :) because spacegraphcats depends on khmer. In bash, you can run `type trim-low-abund.py` to find out where.

I went to look in our documentation and realized we don't mention trim-low-abund anywhere, so I'll fix that. Thanks for asking and my apologies!

You can see some example trimming commands here, from our paper pipeline:

https://github.com/spacegraphcats/2018-paper-spacegraphcats/tree/master/pipeline-base#pipeline-to-generate-files-needed-for-figures-2-and-3

**Comment by susheelbhanu** [comment]
@ctb Thanks a lot for this, and also the additional trimming information!

**Comment by ctb** [comment]
welcome & thanks!

**Comment by ctb** [comment]
added to [doc/running-spacegraphcats.md](https://github.com/spacegraphcats/spacegraphcats/blob/master/doc/running-spacegraphcats.md) in 83e3d7c and 30d4ea2
