### ISSUE TITLE
Discrepancy in Dory test output

### ISSUE THREAD

**Issue by ACharbonneau** [spacegraphcats/spacegraphcats#291]
the install docs have me run a test step using dory, it says I should have output like
```
query inclusion by retrieved contigs: 100.000%
query similarity to retrieved contigs: 100.000%
total time: 0.0s
Finished job 0.
6 of 6 steps (100%) done
```

But my output says I only did 4 steps instead of 6
```
[Wed Aug 12 14:22:07 2020]
Finished job 0.
4 of 4 steps (100%) done
```

I do seem to have all the right output files though.

**Comment by ACharbonneau** [comment]
In the twofoo test I do get 6:
```
[Wed Aug 12 15:06:05 2020]
Finished job 0.
6 of 6 steps (100%) done
```

**Comment by ctb** [comment]
yes, I get the same thing when running

```
python -m spacegraphcats dory-test search
```
per https://github.com/spacegraphcats/spacegraphcats/blob/master/doc/installing-spacegraphcats.md#step-ii-test-spacegraphcats-by-running-a-small-test-dory


-- I'll amend the docs, thanks!
