### ISSUE TITLE
rename `{catlas_base}` directory to something else.

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#316]
right now, the `dory/` and `twofoo/` directories are where the BGZF reads and bcalm output are stored - basically, the cDBG-based things that are generic to multiple catlases. These directories should be named differently, somehow, IMO, because I keep wanting to store the reads and other stuff in them.

**Comment by taylorreiter** [comment]
append with `_catlas`?

**Comment by ctb** [comment]
Well, the naming scheme currently is:

`twofoo` - contains BGZF reads and BCALM cDBG files
`twofoo_k31_r1` - contains catlas

but I'm open to change... I was thinking yesterday that `twofoo.data` or `twofoo_cdbg_k31` or `twofoo_k31` might be good.

**Comment by taylorreiter** [comment]
I like either `twofoo_cdbg_k31` or `twofoo_k31` with a slight preference for the first bc its more informative, although the second is nice because the names would build off of each other nicely.

**Comment by ctb** [comment]
On Sun, Oct 25, 2020 at 09:00:46AM -0700, Taylor Reiter wrote:
> I like either `twofoo_cdbg_k31` or `twofoo_k31` with a slight preference for the first bc its more informative, although the second is nice because the names would build off of each other nicely. 

agree with both opinions - tab completion is super nice, so I'll go with
latter, I think!

**Comment by ctb** [comment]
renamed in #310, to `twofoo_k31`.
