### ISSUE TITLE
Code cleanup (deleting unused/redundant methods)

### ISSUE THREAD

**Issue by sgsmob** [spacegraphcats/spacegraphcats#34]
I can speak directly for `spacegraphcats/catlas.py`, but this may apply to other files in the repo.  `catlas.py` has a lot of methods that may not be used anywhere else.

For example, there are 3 methods `leaves()`, `leaves2()`, and `shadow()` that all find the dominating set nodes that are descendants of the current Catlas node, but they return a different property of the node (node itself, node id, node vertex).  If they are all being used, we should consider a better API to combine them into a single method, but if not, they should be deleted.

There might be a nice tool that detects unused methods, but I don't know of one off the top of my head.

**Comment by luizirber** [comment]
You can check the coverage reports: https://codecov.io/gh/spacegraphcats/spacegraphcats/src/74764972e75d795e8f478bde549379c67fc56cda/spacegraphcats/catlas.py (which might mean you want to test more stuff too? =P)

**Comment by ctb** [comment]
On Fri, Dec 09, 2016 at 11:56:31AM -0800, Luiz Irber wrote:
> You can check the coverage reports: https://codecov.io/gh/spacegraphcats/spacegraphcats/src/74764972e75d795e8f478bde549379c67fc56cda/spacegraphcats/catlas.py (which might mean you want to test more stuff too? =P)

Yes, coverage analysis is the way to go. I think this is something I will
devote part of my christmas break to.
