### ISSUE TITLE
build-catlas.py fails to complete in ~100 hours on a "small" real data set

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#36]
Hi folks,

I ran build-catlas.py on a cDBG constructed from half of a real data set taken from [Hu et al., 2016](http://mbio.asm.org/content/7/1/e01669-15.full), and it failed to complete in 100 hours. (It also required > 60 GB of RAM.)

I will make the gxt and mxt file available today or tomorrow.

**Comment by ctb** [comment]
The data set (gxt/mxt) is available for download [here](http://spacegraphcats.ucdavis.edu.s3.amazonaws.com/hu_catlas.tar.gz).

https://github.com/spacegraphcats/spacegraphcats/blob/master/doc/benchmark-data-sets.md#hu_catlas

**Comment by microgravitas** [comment]
Mike and me have been looking into this, it seems like the algorithm already takes quite long for the first few simple steps. Poling around a bit, I found that replacing the lines
`
            v = next(iter(degbuckets[mindeg]))
            degbuckets[mindeg].remove(v)
`
by the more readable (and sane)
`
            v = degbuckets[mindeg].pop()
`
is a very simple way of halving the running time of this step. I'll fix this and create a pull request soon.

**Comment by sgsmob** [comment]
Even with Felix's fix, we were still unable to get past the `ldo()` (low degree orientation) function in 10 hours.  This is a linear time algorithm and is implemented relatively well, to the extent that I don't know how much more it can be sped up in pure Python.  The program used 62GB of memory, which is a lot but still less than 90% of our server capacity, so I don't think memory ceiling is the real bottleneck.

I will continue to let this job run, but I assume it will also fail to complete in 100 hours.

**Comment by sgsmob** [comment]
Update:  the program appeared not to make any progress in three additional days beyond what it did in the first day.  I don't really understand what is going on but I will look into it further.

**Comment by ctb** [comment]
:) yeah.

I'm happy to microoptimize with Cython but I'm not sure it's a performance
problem.

**Comment by sgsmob** [comment]
What sorts of computation have you been able to do with this data set and 64 GB of memory?  I'm trying to understand to what extent the long run times are inherent to the size of the data set.

**Comment by ctb** [comment]
On Wed, Jan 18, 2017 at 07:35:50AM -0800, sgsmob wrote:
> What sorts of computation have you been able to do with this data set and 64 GB of memory?  I'm trying to understand to what extent the long run times are inherent to the size of the data set.

We can easily assemble it with megahit, we can build a cDBG in not too long (I
think it's less than a day), ...?

**Comment by sgsmob** [comment]
Has anyone done graph analysis on a metagenomic data set of this size?

**Comment by bdsullivan** [comment]
Original flaws in algorithm have been addressed. Able to run on pre-processed version of Hu with current code. If bottleneck re-occurs, please open new issue with specifics.
