### ISSUE TITLE
Timeout option for frontier search

### ISSUE THREAD

**Issue by sgsmob** [spacegraphcats/spacegraphcats#37]
The frontier search is an "anytime" algorithm, which means that at every iteration of the loop, we have a feasible solution.  In other words, we could stop refining the frontier at any time and return its shadow.

Knowing this, we can add an option that lets the user halt the refinement process after a certain amount of time elapses if it has not already terminated.

**Comment by ctb** [comment]
It would be interesting to look at how the "quality" of the match changes over
time, as well; it may be possible to guess at when "good enough" has been
reached.

**Comment by domoritz** [comment]
This is not true for the current search implementation and the search is also relatively fast. I don't think we need premature termination yet.
