### ISSUE TITLE
Mapping between nodes in bcalm cbdg graph and spacegraphcats-custom graph stored in cdbg.txt

### ISSUE THREAD

**Issue by skafaie** [spacegraphcats/spacegraphcats#388]
Thanks for your cool and well-documented work.
I was wondering if there is any output file representing the mapping between nodes in BCALM cdbg (stored in bcalm.unitigs.fa) and your custom format (stored in cbdg.txt). In fact, I need to know the sequence corresponding to each node in the graph you are working with (cbdg.txt).

**Comment by ctb** [comment]
yes! the sequences are renamed to match the `cdbg.gxt` IDs and are then stored in the `bcalm.unitigs.db` file under the `{prefix}_{ksize}` directory, e.g. `twofoo_k31/bcalm.unitigs.db`. This is a sqlite database and you can extract the contigs into FASTA with:
```
python -m spacegraphcats.cdbg.dump_contigs_db_to_fasta twofoo_k31/bcalm.unitigs.db  > out.fa
```
HTH!

**Comment by skafaie** [comment]
Great, thanks a lot!

**Comment by ctb** [comment]
I'll close this for now - but please do post follow-up questions as you have them!

**Comment by skafaie** [comment]
Hi again,
I've noticed that in the new version of spacegraphcats, `bcalm.unitigs.fa` file is not stored in output directories anymore.
Is there any way that we can have access to it?

**Comment by ctb** [comment]
hi, yes! See https://spacegraphcats.github.io/spacegraphcats/developing-spacegraphcats/ - you should be able to run:

```
python -m spacegraphcats.cdbg.dump_contigs_db_to_fasta dory_k21/bcalm.unitigs.db
```

**Comment by skafaie** [comment]
Thanks, but this command only returns the unitigs and their sequences. I need to have the graph you have generated by bcalm (it used to be stored in bcalm.unitigs.fa), but no such file is available in output directories in the new version of spacegraphcats.

**Comment by taylorreiter** [comment]
Hi @somayeh-aut, when I run something like:
```
python -m spacegraphcats run outputs/sgc_conf/G48842_k31_r1_conf.yml extract_contigs extract_reads --nolock --outdir=outputs/sgc_genome_queries --rerun-incomplete
```

I have an output folder `G48842_k31`, inside of which i see:
```
bcalm.inputlist.txt  bcalm_to_gxt.log  bcalm.unitigs.fa.sig  cdbg.gxt         contigs.info.csv  contigs.sig    reads.bgz.index
bcalm.log.txt        bcalm.unitigs.db  bcalm.unitigs.pickle  contigs.indices  contigs.mphf      contigs.sizes
```

I think the `bcam.unitigs.db` is the file you're looking for. To convert it from the `db` format to contigs, you can run: (from: https://github.com/spacegraphcats/spacegraphcats/blob/a71daca5649375c252577d6be602855a88756f61/spacegraphcats/conf/Snakefile#L222
```
python -Werror -m spacegraphcats.cdbg.dump_contigs_db_to_fasta  G48842_k31/bcalm.unitigs.db | gzip > G48842_k31/contigs.fa.gz
```
The `cdbg.gxt` file is the cDBG output by bcalm, in gxt format, which record the edges between nodes in the graph.

Will these two files provide what you're looking for?

**Comment by skafaie** [comment]
Thanks for your response.

What I'd like to do is constructing the subgraph representing nodes matching a query (e.g., available in dory-head.fa.cdbg_ids.txt.gz) and their one-hop neighbors.

To do this in an older version of spacegraphcats, I used to run the command Titus mentioned "python -m spacegraphcats.cdbg.dump_contigs_db_to_fasta twofoo_k31/bcalm.unitigs.db  > out.fa" to find the mapping between your node IDs and those of the original bcalm graph. After that I was able to construct the neighborhood subgraph from the graph available in bcalm.unitigs.fa.

In your new version, since bcalm.unitigs.fa is not available anymore, I don't have access to the graph information.
As you pointed out cdbg.gxt provides edge information but it doesn't include node orientation info (the orientation +/- by which nodes contribute in an edge); therefore I don't think the combination of cdbg.gxt and the mapping file would be enough to construct the neighborhood subgraph I explained.

**Comment by ctb** [comment]
gotcha. I'm on board with restoring this functionality and will look into it. But, gotta ask, is there a reason you're not just running bcalm directly? I'm not sure what sgc adds in this situation :)

**Comment by ctb** [comment]
whoops, never hit "submit" on this --

> Thanks, but this command only returns the unitigs and their sequences. I need to have the graph you have generated by bcalm (it used to be stored in bcalm.unitigs.fa), but no such file is available in output directories in the new version of spacegraphcats.

in addition to @taylorreiter's response, you _should_ be able to run something like

```
python -m spacegraphcats run dory-test build dory_k21/bcalm.unitigs.fa
```
\- that is, specify the file as a target to be built and _kept_, despite the `temporary(...)` flag that we're using. However, it seems like that doesn't work with snakemake, which surprises me. I'll look into that.

**Comment by skafaie** [comment]
Thanks a lot.
I'd like to find the neighborhood graph of a given query. 
I used sgc to find nodes representing this neighborhood and then the next step would be constructing the subgraph consisted of these nodes. 
But now looking at sgc documentation here (https://spacegraphcats.github.io/spacegraphcats/developing-spacegraphcats/) made me wonder if `dory-head.fa.cdbg_ids.txt.gz`  represents the nodes matching the query itself or query neighborhood?

**Comment by ctb** [comment]
> Thanks a lot.
> I'd like to find the neighborhood graph of a given query.

✅ 

> I used sgc to find nodes representing this neighborhood and then the next step would be constructing the subgraph consisted of these nodes.

✅ 

> But now looking at sgc documentation here (https://spacegraphcats.github.io/spacegraphcats/developing-spacegraphcats/) made me wonder if `dory-head.fa.cdbg_ids.txt.gz` represents the nodes matching the query itself or query neighborhood?

yep! it's the neighborhood.

(If you wanted the query itself, you could get that, too, but this is the query neighborhood.)

**Comment by skafaie** [comment]
Great! The neighborhood is what I want! and I'm running `spacegraphcats run <CONFIG.YAML> search` to get that.

**Comment by ctb** [comment]
excellent! please do let us know if you want us to add additional output files etc. we're quite amenable to such things in general and frankly are very excited when people use our software ;)

**Comment by skafaie** [comment]
Thanks. 
I really appreciate it!
Please let me know when the function to build the bcalm graph is ready.
