### ISSUE TITLE
Vertex assignment bug in rdomset.domination_graph

### ISSUE THREAD

**Issue by mogproject** [spacegraphcats/spacegraphcats#390]
The function `spacegraphcats.catlas.rdomset.domination_graph()` does not work as expected. There are cases where a vertex is not assigned to one of its closest dominators.

##### Environment

- OS: macOS Catalina
- Python 3.9.1
- SpaceGraphCats v2.0b11

##### Code

The following code creates a path of four vertices (connected as 0-1-2-3). When we set r=1, the `rdomset()` function chooses two dominators, 0 and 3. Vertex 1's closest dominator is vertex 0, and vertex 2's closest dominator is vertex 3.

```
from io import StringIO
import spacegraphcats.catlas.graph_io as gio
import spacegraphcats.catlas.rdomset as rd

r = 1
G = gio.read_from_gxt(StringIO('4\n0 1\n1 2\n2 3'), r, False)
domset = rd.rdomset(G, r)
dg, dominated = rd.domination_graph(G, domset, r)

print(dominated)
```

##### Expected result

```
SortedDict({0: SortedSet([0, 1]), 3: SortedSet([2, 3])})
```

Each dominator should take exactly one neighbor.

##### Actual result

```
SortedDict({0: SortedSet([0, 1, 2]), 3: SortedSet([3])})
```

Vertex 2 is assigned to vertex 0. This is incorrect because the distance between vertex 0 and 2 is 2, which exceeds the value of r.

Reproducibility rate: 100% (10/10 times bug reproduced)

#### 2. Additional details

For each iteration in lines 276-290 in rdomset.py, a dominator should propagate the assignments to its neighborhood of one larger radius. However, it is possible to propagate more than distance 1.

For instance, if the low-degree orientation is `0 <- 1 <- 2 -> 3`, then vertex 0 propagates to vertex 1, and immediately after that, vertex 1 propagates to vertex 2 before processing vertex 3.

- What if all dominators are labeled earlier than non-dominators?
  - The same issue happens when r > 1. Example: `0 <- 2 <- 3 <- 5 -> 4 -> 1` with dominators `0,1` (5 will belong to 0)
- How bad can assignments go wrong?
  - If there is an induced path of dominators with consecutive labels (such as `1 <- 2 <- 3 <- 4 ...`), the assignment can go arbitrarily wrong.

**Comment by mogproject** [comment]
I made a fix in my forked repository, but before creating a pull request in this repository, I plan to test more instances to see the effects of this fix.
https://github.com/mogproject/spacegraphcats/pull/1

**Comment by ctb** [comment]
thank you! let us know when you want us to take a look :)
