### ISSUE TITLE
Sanity check in rdomset.domination_graph not working

### ISSUE THREAD

**Issue by mogproject** [spacegraphcats/spacegraphcats#423]
https://github.com/spacegraphcats/spacegraphcats/blob/latest/spacegraphcats/catlas/rdomset.py#L297-L298

```
    for v, value in enumerate(assigned_dominator):
        assert value >= 0
```

`enumerate(assigned_dominator)` is equivalent to `enumerate(assigned_dominator.keys())`, and this does not check if all vertices are assigned to some dominator.

This is supposed to be:

```
    for v, value in assigned_dominator.items():
        assert value >= 0
```

or equivalently,

```
    assert(all(value >= 0 for value in assigned_dominator.values()))
```

**Comment by ctb** [comment]
agree - PR? Does it currently pass? 😄

**Comment by mogproject** [comment]
This is problematic only when you call this function directly with a vertex set that is not a dominating set. So, not an issue if you use SpaceGraphCats normally. I will create a PR shortly.

**Comment by mogproject** [comment]
@ctb I made a PR, but I don't know why the GitHub Action failed. Could you please check the details or re-run the action (I don't have permission to do so)?
