### ISSUE TITLE
Parser should make sure that ids are consecutive

### ISSUE THREAD

**Issue by domoritz** [spacegraphcats/spacegraphcats#44]
The parser should ensure that ids are consecutive so that the graph can use a more efficient list for the vertices. For this to work, we also need to return a list that maps back to the original ids. 

We could make the list more efficient if there is a constant offset.

**Comment by sgsmob** [comment]
Are you only dealing with the parser? (i.e. do the graph data structures need to be addressed separately?)

**Comment by domoritz** [comment]
Yes, I'm going to change the parser to return consecutive IDs. You can start changing the graph by manually creating a graph file with IDs 0 to n-1.
