### ISSUE TITLE
Incorrect computation of Catlas node size

### ISSUE THREAD

**Issue by sgsmob** [spacegraphcats/spacegraphcats#48]
When we build a Catlas node using the `create_node()` method, it sets the size of the node to be the sum of the sizes of its children.  I am under the impression that the size should stand for the number of descendants of the current node*.  This, however, is not correctly computed, since it cannot handle the "diamond problem", in which _a_ is the child of both _b_ and _c_ which are both themselves children of _d_.  In this scenario, _a_'s size contributes to _d_ twice.  Empirically, changing 1 or 2 nodes in the dominating set at a single level can lead to a 30% increase in size at the root.

We use the size to weigh the importance of the minhash overlap between the node and the frontier i.e. larger nodes get more preference.  Clearly we can get good results with this mistake, but it definitely introduces a bias we would be better without.

*Even if size isn't intended to refer to the size of the shadow, I can't imagine what we're computing is a meaningful statistic.

**Comment by ctb** [comment]
I have a solution to this based on some minhash theory advances, actually.
Will see if I can write up early next week.

**Comment by bdsullivan** [comment]
Banded minhash addresses this concern.
