### ISSUE TITLE
Use weight for in_neighbor call when possible

### ISSUE THREAD

**Issue by sgsmob** [spacegraphcats/spacegraphcats#50]
Because we are storing the edges in a table whose outer dimension is the weight/label on the edge, if we need to return the in-neighbors of all weights, we have to create a new list to store all of them.  As such, even if every arc has weight 1, not specifying the weight argument is slower than specifying it.  It appears that half the calls to in_neighbors do not specify a weight; we should replace those calls with an explicit weight when possible.

**Comment by domoritz** [comment]
Looks like the only place where we do this is `compute_domset` and I see a lot of potential for optimizations. Is this code too slow, though?

**Comment by bdsullivan** [comment]
We identified this from looking at the top time-consumers during your run on Hu. The following two lines are the relevant ones:

747400468  781.145    0.000 1899.718    0.000 graph.py:60(in_neighbors)
371365234 1118.573    0.000 1118.573    0.000 graph.py:63(<listcomp>)

Even if we could specify the weight in all calls, I think Mike and I agree that we'd only gain about 400 seconds on the run, so it's not a top priority in terms of overall efficiency, just something that we shouldn't be sloppy about as we move to doing even more domset calculations.
