### ISSUE TITLE
what does build_catlas output?

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#55]
```
python -m spacegraphcats.build_contracted_dbg -k 31 -M 1e8 data/acido-short.fa
python -m spacegraphcats.build_catlas acido-short 1
```

produces only one file, `acido-short.aug.0.ext`. Is that correct? What's the relationship of this file to the domgraph?

**Comment by sgsmob** [comment]
We have not integrated `build_catlas.py` back into the existing workflow, which was probably a mistake.  Thus far, we have been building catlases by running `catlas.py` (run with `-h` option to see arguments)

**Comment by sgsmob** [comment]
The `.aug.{i}.ext` files are saved versions of the DTF augmentations, which allows us to go back and compute a i+1 augmentation without redoing the first i steps.  I don't think the current catlas construction actually does this caching, but it could be added back as desired.

**Comment by ctb** [comment]
ok - so now

```
python -m spacegraphcats.build_contracted_dbg -k 31 -M 1e9 data/acido.fa
python -m spacegraphcats.catlas acido/acido.gxt acido/acido.catlas acido/acido.domgraph 1
```

produces

```
ls -la acido
total 3248
drwxr-xr-x   6 t  staff      204 Apr 24 06:21 .
drwxr-xr-x  39 t  staff     1326 Apr 24 06:20 ..
-rw-r--r--   1 t  staff    28486 Apr 24 06:21 acido.catlas
-rw-r--r--   1 t  staff        0 Apr 24 06:21 acido.domgraph
-rw-r--r--   1 t  staff    22826 Apr 24 06:21 acido.gxt
-rw-r--r--   1 t  staff  1609623 Apr 24 06:21 acido.mxt
```
 - should acido.domgraph be empty?

and what's the format of acido.catlas? thx :)

**Comment by sgsmob** [comment]
The catlas output is a csv with each line being a node whose fields are:

- CAtlas node index
- cDBG vertex identifying the node
- node level
- list of indices of children, separated by spaces

**Comment by sgsmob** [comment]
The domgraph file should not be empty.  I can fix this bug on my end, or if it would be easier, you can move lines 53 and 54 of catlas.py to line 67 (i.e. don't increase the level before checking if it's 0).

**Comment by ctb** [comment]
ok! fixed in digraph_ctb (as soon as I push). Then the domgraph file is `<node> <connected nodes in domgraph>`?

**Comment by sgsmob** [comment]
Yes

**Comment by ctb** [comment]
ok, and it looks like in the catlas, you recover the cDBG <-> dom node mapping by looking at the level 0 nodes? e.g. `500,1199,0` means that cDBG node 1199 is dominating set node 500, and `1100,1200,1,500 501 502 691` means that domset node 500 (and 501 etc) are under domgraph node 1100 which is level 1 in the catlas?

**Comment by sgsmob** [comment]
the line `500,1199,0` means that the _CAtlas_ node 500 is associated with cDBG vertex 1199.

the line `1100,1200,1,500 501 502 691` means that CAtlas node 1100, which has cDBG vertex 1200 as its dominator dominates the CAtlas nodes 500, 501, etc.  So you need to look at the CAtlas node with index 500 to find out which cDBG vertex is actually dominated there.

**Comment by ctb** [comment]
if you could check me, I would appreciate it ;).

see:

https://github.com/spacegraphcats/spacegraphcats/blob/digraph_ctb/ctb/make-sbt-of-mxt.py#L34

which goes through the catlas file twice:

first, it loads the catlas level 0 nodes, and builds a mapping from catlas node to cdbg node.

then it goes through again, and for each level *1* node, it links that catlas node to the original underlying cdbg node.

The goal is to get the catlas-level-1 -> cdbg mapping.

(obviously the code can be more efficient, but I am trying to make sure I'm doing the right thing first!)

This seems to not fail, but the final mapping only contains 980 cdbg nodes, while the GXT file has 2140 cdbg nodes in it.

**Comment by sgsmob** [comment]
I wouldn't expect this code to capture all nodes in the GXT file.  Since the vertices that are never dominators are not stored anywhere in the catlas, those would fail to show up in this mapping.  You would need to extract those from the domgraph file.

But otherwise, this code appears to correctly determine which vertices that are dominators at the base level (0) are dominated by which level 1 nodes.

**Comment by sgsmob** [comment]
In the catlas file, the children field will always be blank for leaf nodes, even though conceptually it would make sense to list all the cDBG nodes that are dominated by that node.  You have indicated that this would make the catlas files too large, so we are essentially simulating that behavior by offloading that first domination relationship to the domgraph file.

**Comment by ctb** [comment]
wait, the domgraph file contains `<node> <connected nodes in domgraph>`... those are all cdbg node IDs? as usual I'm clearly confused ;)

the line `6 6 959 960 961` says cdbg node 6 is connected to cdbg node 959 in the domgraph?

(note that in that file we can maybe eliminate the node itself from the list, as in '6' doesn't need to be in its own list of connected nodes)

**Comment by sgsmob** [comment]
I misunderstood your previous description of the domgraph file.  The domgraph file is not actually a graph, so we should probably rename it.  It just contains a cDBG node followed by all the cDBG nodes it optimally dominates.  I agree that we can eliminate the node itself.

Is there a downstream computation where we actually need the first level domgraph?  Or is it sufficient to only mark the first domination relationship as I described above.

**Comment by ctb** [comment]
ok!

not sure about the need for first-level domgraph. and yes, we should rename the domgraph file :) - please do so at your convenience!

**Comment by sgsmob** [comment]
I suppose actually it's up to you, the user, to rename it!  The file name is supplied as a command line argument to catlas.py.  The command line argument and variable names all just call it a domination file, so I actually think the code as is captures the correct behavior.

**Comment by ctb** [comment]
oh! ok
