### ISSUE TITLE
Don't save empty minhashes

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#73]
My guess is that `make_catlas_minhashes` ends up saving a lot of zero-length minhashes into pickle files. These can be omitted without consequence, presumably :)

**Comment by domoritz** [comment]
The assumption is that nodes without minhashes have a small shadow, right? We should be able to ignore them during search but I could see how it also makes sense to always include these nodes in the output.

**Comment by ctb** [comment]
+1 to include them
