### ISSUE TITLE
New search results.

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#8]
[Results of running search against the original cDBG](https://github.com/spacegraphcats/spacegraphcats/blob/master/doc/evaluating%20search%20on%20the%20cDBG.ipynb) - we can achieve quite high sensitivity & specificity with even the small MinHashes. (>99% sensitivity, 100% specificity).

(Please see the discussion at the top of the above notebook!)

[Results of running previous domgraph searches but now weighting by size of original cDBG nodes](https://github.com/spacegraphcats/spacegraphcats/blob/report_size/doc/plot-benchmark-sens-spec.ipynb) - not much changes, but it's probably the right way to benchmark. Also see associated PR https://github.com/spacegraphcats/spacegraphcats/pull/7.

[Results of running previous domgraph search with size weighting and also at searchlevel=2 instead of 3](https://github.com/spacegraphcats/spacegraphcats/blob/searchlevel2/doc/plot-benchmark-sens-spec.ipynb) -- very much better than with searchlevel 3...

**Comment by bdsullivan** [comment]
No remaining to-do items associated.
