### ISSUE TITLE
Create shadow() method on CAtlas

### ISSUE THREAD

**Issue by bdsullivan** [spacegraphcats/spacegraphcats#80]
Translates a set of nodes into the cDBG nodes that they dominate.

**Comment by domoritz** [comment]
- Also move the load_dag method over to the the catlas (#77)

**Comment by ctb** [comment]
We had talked about keeping the search code separate from the creation
code; I like that idea.

**Comment by domoritz** [comment]
Oh, I thought we wanted to make sure that the creation code never loads from the search code so that it doesn't have to know about minhashes for example. I didn't know we also want it to be the other way around.

I like that, though. So let's close this.

**Comment by ctb** [comment]
On Wed, May 03, 2017 at 04:31:29PM -0700, Dominik Moritz wrote:
> Oh, I thought we wanted to make sure that the creation code never loads from the search code so that it doesn't have to know about minhashes for example. I didn't know we also want it to be the other way around.
> 
> I like that, though. So let's close this. 

ahh, ok, good clarification :)

I think part of the hope was that we (TiP specifically) could use the
spacegraphcats code more broadly, and I think a small API to read the
results of the (larger, more complicated) spacegraphcats code base would
further that goal.  Then we can build off of that API.  For now that
API can just be a few dozen lines of Python code in the same repo, of course ;)
