### ISSUE TITLE
Store file information for cDBG domination so that we can compute the full shadow. 

### ISSUE THREAD

**Issue by bdsullivan** [spacegraphcats/spacegraphcats#81]
Should the CAtlas know what file it can use to translate leaves to shadow? If so, where should we store this pointer? In every node?

**Comment by domoritz** [comment]
We don't need to store the pointer to the file. Instead, we should store the name of the directory that the catlas, minhashes, and the cDBG are in.

**Comment by domoritz** [comment]
We decided to store it in every CAtlas node.

**Comment by sgsmob** [comment]
Isn't this predetermined based on the naming conventions?

**Comment by ctb** [comment]
This all works with the latest file naming structure. I'll close; feel free to reopen if I misunderstood!
