### ISSUE TITLE
what about making files in the catlas subdirs have standard names?

### ISSUE THREAD

**Issue by ctb** [spacegraphcats/spacegraphcats#89]
Right the directory and the files share the same prefix -- 15genome/15genome.catlas, for example.

This makes copying and renaming catlas work directories annoying - you have to rename all the files in the directory. I could write a script to do this, but 'mv' is pretty convenient... :).

How about:

* removing the prefix for files in the directory;
* automatically generating a little log file of commands that have been run;

? If no objections we can work on this slowly, with the first priority being to remove the prefix.

**Comment by sgsmob** [comment]
I like this idea.
